services:
    api:
        build: .
        ports:
        - "8080:8080"
        depends_on:
            db:
                condition: service_started
    db:
        container_name: pgdb
        image: postgres:16.0
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
        ports:
        - "5432:5432"
        volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./src/main/resources/db/sql-scripts:/docker-entrypoint-initdb.d/

volumes:
    postgres_data:
